import type { EventData } from "../types";

export const sampleEvents: EventData[] = [
    {
        id: '1',
        title: 'Anti-Corruption March - Kathmandu',
        description: 'Join us for a peaceful march demanding transparency and accountability from our leaders. We will gather at Basantapur and march to Singha Durbar.',
        date: '2024-01-15',
        time: '10:00 AM',
        location: 'Basantapur, Kathmandu',
        organizer: {
            name: 'Youth for Change',
            avatarUrl: '/logoexample.jpg',
        },
        imageUrl: '/images/current_20_pack_box.jpg',
        attendees: 245,
        maxAttendees: 500,
        category: 'protest',
        status: 'upcoming',
    },
    {
        id: '2',
        title: 'Community Workshop: Understanding Your Rights',
        description: 'Learn about your constitutional rights and how to exercise them effectively. Interactive session with legal experts.',
        date: '2024-01-20',
        time: '2:00 PM',
        location: 'Community Center, Patan',
        organizer: {
            name: 'Citizens Voice',
            avatarUrl: '/logoexample.jpg',
        },
        imageUrl: '/images/khaja_pack.jpg',
        attendees: 78,
        maxAttendees: 100,
        category: 'workshop',
        status: 'upcoming',
    },
    {
        id: '3',
        title: 'Fundraising Dinner for Legal Aid',
        description: 'Support our legal aid fund to help citizens fight corruption cases. Enjoy traditional Nepali dinner while supporting a cause.',
        date: '2024-01-25',
        time: '7:00 PM',
        location: 'Hotel Yak & Yeti, Kathmandu',
        organizer: {
            name: 'Grassroots Nepal',
            avatarUrl: '/logoexample.jpg',
        },
        imageUrl: '/images/wai_wai.jpg',
        attendees: 120,
        maxAttendees: 150,
        category: 'fundraiser',
        status: 'upcoming',
    },
    {
        id: '4',
        title: 'Strategy Meeting: Next Steps',
        description: 'Planning session for upcoming campaigns and initiatives. All active members are encouraged to attend.',
        date: '2024-01-12',
        time: '6:00 PM',
        location: 'Online (Zoom)',
        organizer: {
            name: 'Enough is Enough',
            avatarUrl: '/logoexample.jpg',
        },
        attendees: 45,
        category: 'meeting',
        status: 'upcoming',
    },
    {
        id: '5',
        title: 'Rally Against Land Corruption',
        description: 'Stand with farmers whose land has been illegally seized. We demand justice and land rights protection.',
        date: '2024-01-08',
        time: '11:00 AM',
        location: 'Tundikhel, Kathmandu',
        organizer: {
            name: 'Farmers United',
            avatarUrl: '/logoexample.jpg',
        },
        imageUrl: '/images/sel_roti_pack.jpg',
        attendees: 189,
        category: 'protest',
        status: 'completed',
    },
];
